// get docter request

export const GET_DOCTERS_REQUEST = "GET_DOCTER_REQUEST";
export const GET_DOCTERS_SUCCESS = "GET_DOCTER_SUCCESS";
export const GET_DOCTERS_FAILURE = "GET_DOCTER_FAILURE";

//  POST REQUEST
export const POST_DOCTER_REQUEST = "POST_DOCTER_REQUEST";
export const POST_DOCTER_SUCCESS = "POST_DOCTER_SUCCESS";
export const POST_DOCTER_FAILURE = "POST_DOCTER_FAILURE";

//  PUT REQUEST
export const PUT_DOCTER_REQUEST = "PUT_DOCTER_REQUEST";
export const PUT_DOCTER_SUCCESS = "PUT_DOCTER_SUCCESS";
export const PUT_DOCTER_FAILURE = "PUT_DOCTER_FAILURE";

//  DELETE REQUEST
export const DELETE_DOCTER_REQUEST = "DELETE_DOCTER_REQUEST";
export const DELETE_DOCTER_SUCCESS = "DELETE_DOCTER_SUCCESS";
export const DELETE_DOCTER_FAILURE = "DELETE_DOCTER_FAILURE";